name: pinn-bioenergetic
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.17.1
  - matplotlib=3.10.9
  - pytorch=2.11.0
  - pip
  # Optional:
  # - jupyter
  # - ipykernel
